bno08x_driver:
  ros__parameters:

    frame_id: "bno085"  # The frame_id to use for the sensor data

    # Communication Interface
    # Select the communication interface to use 
    # (only one interface can be enabled at a time)
    # This requires a hardware change to the board
    # (see documentation for more information)
    i2c:
      enabled: false
      bus: "/dev/i2c-5"
      address: "0x4B"

    publish:
      magnetic_field: 
        enabled: false
        rate: 100   # max 100 Hz
      imu:
        enabled: true
        rate: 100   # max 400 Hz 
                    # (anythihng above 100Hz depends on your hardware)


    spi:
      enabled: true
      device: "/dev/spidev4.1" # name of device which spiinterface gets in
      INT: 35 # int number of INT GPIO
      WAK: 59 # int number of WAK GPIO
      RST: 58 # int number of RST GPIO

